---
title: "STOR 664 HW 2"
author: "Brian N. White"
date: "9/9/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Problem 20

```{r}
library(data.table)
mydat <- fread('http://rls.sites.oasis.unc.edu/faculty/rs/source/Data/dmark.dat')
#pull in data from website
head(mydat)

colnames(mydat)[] <- c("week", "mark", "pound")
#give variables descriptive names
colnames(mydat)

attach(mydat)
#column names of mydat recognized independently
```

$\textbf{(a)}$

Note, there is strong visual evidence of autocorrelation in the time series.
```{r}
par(mfrow=c(2, 2))
plot(mark~week)
plot(pound~week)
plot(pound~mark)
```
$\textbf{(b)}$

Assume the individaul weekly observaions are independent. The linear regression equation $\hat y_{i}=\hat\beta_{0}+\hat\beta_{1}x_{i}$ is computed via the code below. A point estimate for $\hat\beta_{1}$ is approximately $-2.9$ with a 90% confidence interval of $[-5.12, -0.69]$.
```{r}
mp_lm <- lm(pound~mark)
summary(mp_lm)
confint(mp_lm, level=0.90)

plot(pound~mark)
abline(mp_lm, col="blue")
```

